name: sociocube
description: "Discover and connect with UGC creators, explore influencer marketing campaigns, and earn as a content creator."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloudflare_turnstile: ^3.2.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_hooks: ^0.21.3+1
  flutter_secure_storage: ^9.2.2
  flutter_riverpod: ^3.0.0
  go_router: ^14.2.7
  jwt_decoder: ^2.0.1
  hooks_riverpod: ^3.0.0
  http: ^1.5.0
  graphql_flutter: ^5.2.1
  graphql: ^5.2.3
  image_picker: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.2
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  graphql_codegen: ^3.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo/
    - lib/core/constants/countries.json

  fonts:
    - family: Sans
      fonts:
        - asset: assets/fonts/sans.ttf
    - family: Serif
      fonts:
        - asset: assets/fonts/serif.ttf
        - asset: assets/fonts/serif-italic.ttf
          style: italic

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/app_icon.png"
  min_sdk_android: 21
